# SPDX-License-Identifier: Apache-2.0

# frozen_string_literal: true

#--
# Copyright 2024 Joel E. Anderson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#++

module Wrapture
  # A Python project that builds a module by creating a pyproject.toml file as
  # described in PEP 517.
  class PyprojectBuild
    include Build

    # Build information for the Python module.
    attr_reader :python_build

    # Create a pyproject build for a Python module.
    def initialize(python_build)
      @python_build = python_build
    end

    # A pyproject.toml file that could be used to build this module.
    #
    # CMake is a common build system for C++ projects. It uses a file named
    # CMakeLists.txt to describe how to build a project, including information
    # about the source files and any dependencies required.
    def pyproject
      sources = @python_build.module_sources.map do |src|
        "\"#{src}\""
      end.join(', ')

      libraries = @python_build.module_links.map do |lib|
        "\"#{lib}\""
      end.join(', ')

      file = SourceFile.new('pyproject.toml')

      file.puts <<~PYPROJECTTEXT
        [project]
        name = "#{@python_build.name}"
        version = "1.0" # TODO: create a scope version number
        description= "generated by wrapture" # TODO: pass the description into the build

        [tool.setuptools]
        ext-modules = [
          {name="#{@python_build.name}", language="c", sources=[#{sources}], libraries=[#{libraries}]}
        ]

        [build-system]
        requires = ["setuptools>=74.1"]
        build-backend = "setuptools.build_meta"
      PYPROJECTTEXT

      file
    end

    # All source files in this module.
    #
    # This includes pyproject.toml as well as the sources of the underlying
    # Python module build.
    def sources
      [pyproject] + @python_build.sources
    end
  end
end
