# SPDX-License-Identifier: Apache-2.0

# Copyright 2025-2026 Joel E. Anderson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module Wrapture
  module Wrapper
    module CToPython
      extend Wrapper

      def self.add_class_object: (SourceFile, ClassSpec) -> SourceFile
      def self.add_enum_object: (SourceFile, EnumSpec) -> SourceFile
      def self.add_module_objects: (SourceFile, Context) -> SourceFile
      def self.allocator_params: () -> Enumerable[CSource::CDeclaration]
      def self.arg_parse_format: (Enumerable[String], ?Enumerable[String]) -> String
      def self.base_type_object: (ClassSpec) -> String?
      def self.cast_equivalent: (ClassSpec, String, String) -> String
      def self.class_members_declaration: (ClassSpec) -> CSource::CDeclaration
      def self.class_methods_declaration: (ClassSpec) -> CSource::CDeclaration
      def self.class_struct: (Context, ?var_name: String) -> String
      def self.class_struct_pointer: (Context, ?var_name: String) -> String
      def self.class_type_object_declaration: (ClassSpec) -> CSource::CDeclaration
      def self.class_type_struct: (ClassSpec) -> CSource::CStruct
      def self.constructor_params: () -> Enumerable[CSource::CDeclaration]
      def self.constructors_overloaded?: (ClassSpec) -> bool
      def self.create_python_object: (TypeSpec, String) -> String
      def self.create_self: (CSource::CBlock, ClassSpec) -> CSource::CBlock
      def self.declare_module_struct: (SourceFile, String) -> SourceFile
      def self.declare_wrapper_locals: (CSource::CBlock, FunctionSpec) -> CSource::CBlock
      def self.declare_wrapper_param_locals: (CSource::CBlock, FunctionSpec) -> CSource::CBlock
      def self.default_allocator: (ClassSpec) -> CSource::CFunction
      def self.default_destructor: (ClassSpec) -> CSource::CFunction
      def self.define_class_functions: (CSource::CBlock, Context) -> CSource::CBlock
      def self.define_module: (Context) -> CSource::CSourceFile
      def self.define_module_init: (SourceFile, Context) -> SourceFile
      def self.destructor_wrapper: (Context) -> CSource::CFunction
      def self.enum_constructor: (EnumSpec) -> CSource::CFunction
      def self.equivalent_member_declaration: (ClassSpec) -> CSource::CDeclaration
      def self.factory_constructor: (ClassSpec) -> CSource::CFunction
      def self.finalize_module_types: (CSource::CBlock, Context) -> SourceFile
      def self.function_arg_parse_format: (FunctionSpec) -> String
      def self.function_wrapper: (Context) -> CSource::CFunction
      def self.function_wrapper_name: (Context) -> String
      def self.initialize_optional_params: (CSource::CBlock, FunctionSpec) -> CSource::CBlock
      def self.member_constructor: (ClassSpec) -> CSource::CFunction
      def self.member_constructor?: (ClassSpec) -> bool
      def self.member_constructor_arg_parse_format: (ClassSpec) -> String
      def self.member_constructor_call: (ClassSpec) -> String
      def self.member_constructor_overload_wrapper: (ClassSpec) -> CSource::CFunction
      def self.member_constructor_parse_tuple_call: (ClassSpec) -> String
      def self.member_constructor_parsing_wrapper: (ClassSpec) -> CSource::CFunction
      def self.member_type: (TypeSpec) -> String
      def self.method_flags: (FunctionSpec) -> String
      def self.module_includes: (Context) -> Array[CSource::CInclude]
      def self.no_args_wrapper: (Context) -> CSource::CFunction
      def self.overload_dispatcher: (Enumerable[FunctionSpec]) -> CSource::CFunction
      def self.overload_groups: (Context) -> Hash[String, Array[FunctionSpec]]
      def self.overload_wrapper: (Context) -> CSource::CFunction
      def self.overload_wrapper_call: (FunctionSpec) -> String
      def self.overload_wrapper_name: (FunctionSpec) -> String
      def self.param_format: (FunctionSpec, ParamSpec) -> String
      def self.param_uses_equivalent?: (Context, CSource::CDeclaration) -> bool
      def self.parse_tuple_call: (FunctionSpec) -> String
      def self.parsing_wrapper: (Context) -> CSource::CFunction
      def self.resolve_action_value: (FunctionSpec, String) -> String
      def self.resolve_wrapped_param: (FunctionSpec, CSource::CDeclaration) -> String
      def self.return_statement: (FunctionSpec) -> String
      def self.runtime_base_size: (ClassSpec) -> String
      def self.runtime_class?: (ClassSpec) -> bool
      def self.runtime_type_cast: (ClassSpec, String) -> String
      def self.self_declaration: (ClassSpec) -> CSource::CDeclaration
      def self.source_return_type: (FunctionSpec) -> untyped
      def self.type_object_name: (Named class_spec) -> String
      def self.type_object_pointer: (ClassSpec class_spec) -> (String | nil)
      def self.type_struct_name: (Named class_spec) -> String
      def self.wrap_class_context: (Context) -> PythonSource::PythonSourceSet
      def self.wrap_constant_context: (Context) -> PythonSource::PythonSourceSet
      def self.wrap_enum_context: (Context) -> PythonSource::PythonSourceSet
      def self.wrap_function_context: (Context) -> PythonSource::PythonSourceSet
      def self.wrap_namespace_context: (Context) -> PythonSource::PythonSourceSet
      def self.wrapped_error_check: (Context) -> Array[untyped]
      def self.wrapped_function_call: (Context) -> String
      def self.wrapper_param_locals: (FunctionSpec) -> Enumerable[CSource::CDeclaration]
      def self.wrapper_return_type: (FunctionSpec) -> untyped
    end
  end
end