AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  Max: 350

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 55

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/GuardClause:
  Enabled: false
