require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  Max: 700

Metrics/BlockLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 55

Metrics/PerceivedComplexity:
  Max: 10

Minitest/AssertWithExpectedArgument:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 10

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/GuardClause:
  Enabled: false
