language: ruby

os:
  - linux
  - osx

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby

matrix:
  include:
    - os: linux
      dist: trusty
      rvm: truffleruby
    - os: osx
      rvm: truffleruby
      gemfile: gemfiles/osx_truffle.gemfile
    - os: linux
      dist: trusty
      rvm: rbx-3

before_install:
  - gem update --system
  - if [[ $TRAVIS_RUBY_VERSION =~ "truffle" ]]; then gem install bundler -v 1.17.3 --no-document; else gem install bundler --no-document; fi

script:
  - if [[ $TRAVIS_RUBY_VERSION =~ "2.6" ]]; then bundle exec rubocop; fi
  - bundle exec rake test
  - gem build wrapture.gemspec
  - gem install wrapture
