language: ruby

os:
  - linux
  - osx

rvm:
#  - 1.9.3
#  - 2.0
#  - 2.1
#  - 2.2
#  - 2.3
#  - 2.4
#  - 2.5
  - 2.6
  - jruby
  - truffleruby

matrix:
  include:
    - os: linux
      dist: trusty
      rvm: rbx-3
    - os: osx
      osx_image: xcode8
      rvm: rbx-3

script:
  - gem build wrapture.gemspec
  - gem install wrapture
