language: ruby

os:
  - linux
  - osx

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby
  - truffleruby

matrix:
  include:
    - os: linux
      dist: trusty
      rvm: rbx-3

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec rake test
  - gem build wrapture.gemspec
  - gem install wrapture
