# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - roadmap.md
  - rdoc/index.html

# default exclusion list
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
