# SPDX-License-Identifier: Apache-2.0

# Copyright 2025-2026 Joel E. Anderson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module Wrapture
  module CSource
    def self.format_block: (CBlock) -> Enumerable[String]
    def self.format_declaration: (CDeclaration) -> Enumerable[String]
    def self.format_expression: (CExpression) -> Enumerable[String]
    def self.format_function_declaration: (CFunction) -> Enumerable[String]
    def self.format_function_definition: (CFunction) -> Enumerable[String]
    def self.format_if: (CIf) -> Enumerable[String]
    def self.format_initialization: (CDeclaration) -> Enumerable[String]
    def self.format_struct: (CStruct) -> Enumerable[String]
    def self.indent: (untyped) -> Enumerable[String]
  end
end