# SPDX-License-Identifier: Apache-2.0

# Copyright 2025-2026 Joel E. Anderson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

type class_hash = Hash[Symbol, (bool | Enumerable[function_hash] | Hash[Symbol, name_type] | name_type)]

module Wrapture
  class ClassSpec
    include Named

    @doc: Comment
    @exception: bool
    @name_words: Array[String]
    @parent: Array[String] | nil
    @source: Hash[Symbol, CSource::CStruct]

    attr_accessor doc: Comment
    attr_writer exception: bool
    attr_reader name_words: Array[String]
    attr_accessor parent: Array[String] | nil
    attr_reader source: Hash[Symbol, CSource::CStruct]

    def self.from_hash: (class_hash) -> Wrapture::ClassSpec
    def self.validate_hash: (class_hash) -> void

    private def self.set_source_from_hash: (FunctionSpec, Hash[Symbol, untyped]) -> void

    def initialize: (name_type) -> void
    def []: (Symbol) -> CSource::CStruct
    def []=: (Symbol, CSource::CStruct) -> CSource::CStruct
    def child?: -> bool
    def exception?: -> bool
  end
end
