module Wrapture
  class Comment
    def self.validate_doc: (untyped doc) -> nil
    attr_reader text: String
    def initialize: (?String comment) -> String
    def empty?: -> bool
    def format: (?line_prefix: String, ?first_line: String?, ?last_line: String?, ?max_line_length: Integer) ?{ (String) -> untyped } -> nil
    def format_as_doxygen: (?max_line_length: Integer) { (String) -> void } -> nil

    private
    def paragraphs: (Complex | Float | Integer | Rational line_length) { (String) -> untyped } -> untyped
  end
end
