module Wrapture
  EQUIVALENT_STRUCT_KEYWORD: String
  EQUIVALENT_POINTER_KEYWORD: String
  RETURN_VALUE_KEYWORD: String
  SELF_REFERENCE_KEYWORD: String
  TEMPLATE_USE_KEYWORD: String
  KEYWORDS: Array[String]
end
