module Wrapture
  class ConstantSpec
    @spec: spec_hash
    @doc: Wrapture::Comment
    @type: Wrapture::TypeSpec

    def self.normalize_spec_hash: (spec_hash spec) -> spec_hash
    def initialize: (spec_hash spec) -> void
    def declaration_includes: -> Array[String]
    def definition_includes: -> Array[String]
    def declaration: { (String) -> void } -> void
    def definition: (String class_name) -> String
  end
end
