# SPDX-License-Identifier: Apache-2.0

# Copyright 2025 Joel E. Anderson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module Wrapture
  class ConstantSpec
    include Named

    @spec: spec_hash
    @doc: Wrapture::Comment
    @type: Wrapture::TypeSpec

    def self.normalize_spec_hash: (spec_hash spec) -> spec_hash
    def initialize: (spec_hash spec) -> void
    attr_reader doc: Wrapture::Comment
    attr_reader type: Wrapture::TypeSpec
    def declaration_includes: -> Array[String]
    def definition_includes: -> Array[String]
    def declaration: { (String) -> void } -> void
    def definition: (String class_name) -> String
    def name_words: -> Array[String]
    def value: -> String
  end
end
