module Wrapture
  class EnumSpec
    @spec: untyped
    @doc: untyped

    def self.normalize_spec_hash: (untyped spec) -> untyped
    def self.normalize_spec_hash!: (untyped spec) -> untyped
    def initialize: (untyped spec) -> void
    def name: -> untyped
    def definition_contents: { (?String) -> void } -> void

    private
    def definition_includes: -> untyped
    def element_definition: (untyped element) { (String) -> void } -> void
    def element_doc: (untyped element) { (untyped) -> void } -> untyped
    def header_guard: -> String
  end
end
