module Wrapture
  class WraptureError < StandardError
  end

  class InvalidDoc < WraptureError
  end

  class InvalidTemplateUsage < WraptureError
  end

  class InvalidSpecKey < WraptureError
    def initialize: (String message, ?valid_keys: Array[String]) -> void
  end

  class MissingSpecKey < WraptureError
  end

  class MissingNamespace < WraptureError
  end

  class UndefinableSpec < WraptureError
  end

  class UnsupportedSpecVersion < WraptureError
  end

  class WrapError < WraptureError
  end
end
