module Wrapture
  class FunctionSpec
    include Named

    @owner: Wrapture::ClassSpec | Wrapture::Scope
    @spec: spec_hash
    @wrapped: Hash[Symbol, untyped] | nil
    @params: Array[Wrapture::ParamSpec]
    @constructor: bool
    @destructor: bool

    attr_reader owner: Wrapture::ClassSpec | Wrapture::Scope
    attr_reader params: Array[Wrapture::ParamSpec]
    attr_reader return_type: Wrapture::TypeSpec
    attr_accessor wrapped: Hash[Symbol, untyped] | nil

    def self.from_hash: (spec_hash spec) -> Wrapture::FunctionSpec

    private def self.wrapped_from_hash: (Hash[Symbol, untyped]) -> void

    def initialize: (spec_hash spec, ?(Wrapture::ClassSpec | Wrapture::Scope) owner, ?constructor: bool, ?destructor: bool) -> void
    def constructor?: -> bool
    def declaration_includes: -> Array[String]
    def definable?: (?lang: Symbol) -> bool
    def definition_includes: -> Array[String]
    def destructor?: -> bool
    def doc: -> Wrapture::Comment
    def initializers: -> spec_hash
    def libraries: -> Array[String]
    def name_words: -> Array[String]
    def optional_params: -> Array[Wrapture::ParamSpec]
    def overloaded?: -> bool
    def param_names: -> Array[String]
    def params?: -> bool
    def qualified_name: -> String
    def required_params: -> Array[Wrapture::ParamSpec]
    def resolved_return: -> Wrapture::TypeSpec
    def return_expression: (?func_name: String) -> String
    def resolve_type: (Wrapture::TypeSpec type_spec) -> Wrapture::TypeSpec
    def return_overloaded?: -> bool
    def static?: -> bool
    def to_s: () -> String
    def variadic?: -> bool
    def virtual?: -> bool
    def void_return?: -> bool
  end
end
