# SPDX-License-Identifier: Apache-2.0

# Copyright 2025-2026 Joel E. Anderson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

type type_hash = Hash[Symbol, name_type]

module Wrapture
  class TypeSpec
    include Named

    @name_words: Array[String]

    ANY_TYPE_NAME: Array[String]
    INT_TYPE_NAME: Array[String]
    SELF_TYPE_NAME: Array[String]
    STRING_TYPE_NAME: Array[String]
    VOID_TYPE_NAME: Array[String]

    attr_reader name_words: Array[String]

    def self.from_hash: (type_hash) -> TypeSpec

    def initialize: (name_type) -> void
    def ===: (ClassSpec | EnumSpec) -> bool
    def any?: () -> bool
    def int?: () -> bool
    def self?: () -> bool
    def string?: () -> bool
    def to_s: -> String
    def void?: () -> bool
  end
end
