module Wrapture
  class TypeSpec
    include Named

    @spec: spec_hash

    def self.normalize_spec_hash: (spec_hash | String spec) -> spec_hash
    def self.normalize_spec_hash!: (spec_hash | String spec) -> spec_hash
    def initialize: (?String spec) -> untyped
    def ==: (untyped other) -> untyped
    def base: -> String
    def equivalent_pointer?: -> bool
    def equivalent_struct?: -> bool
    def function: -> (Wrapture::FunctionSpec | nil)
    def function?: -> bool
    def includes: -> untyped
    def name: -> String
    def pointer?: -> bool
    def resolve: (Wrapture::FunctionSpec owner) -> Wrapture::TypeSpec
    def self_reference?: -> bool
    def to_s: -> String
    def variadic?: -> bool
  end
end
