module Wrapture
  class WrappedFunctionSpec
    @spec: spec_hash
    @error_rules: untyped
    @error_action: untyped

    def self.normalize_spec_hash: (untyped spec) -> untyped
    def initialize: (untyped spec) -> void
    def call_from: (untyped function_spec) -> String
    def error_check: (?return_val: String)  { (String) -> void } -> void
    def error_check?: -> bool
    def includes: -> untyped
    def return_val_type: -> untyped
    def use_return?: -> bool
  end
end
