name: build
on:
  push:
  pull_request:
    branches:
      - latest
      - release
  schedule:
    - cron: '18 6 * * 2'
jobs:
  matrix-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4', 'jruby-9.4.12', 'truffleruby-head']
    name: ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: |
          bundle config set --local without 'development'
          bundle install
      - name: Run Tests
        run: bundle exec rake test
      - name: Upload to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: coverage/coverage.xml
      - name: Build Gem
        run: gem build wrapture.gemspec
      - name: Install Gem
        run: gem install wrapture
  cpp:
    runs-on: ubuntu-latest
    name: c++ runtime tests
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: '3.4'
      - name: Install Ruby Dependencies
        run: |
          bundle config set --local without 'development'
          bundle install
      - name: Run C++ Examples
        run: bundle exec rake examples:cpp
  python:
    runs-on: ubuntu-latest
    name: python integration tests
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: '3.4'
      - name: Install Ruby Dependencies
        run: |
          bundle config set --local without 'development'
          bundle install
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
      - name: Install Prereqs
        run: pip3 install build setuptools
      - name: Run Python Tests
        run: bundle exec rake test:integration:python
      - name: Run Python Examples
        run: bundle exec rake examples:python
  docker:
    runs-on: ubuntu-latest
    name: docker build
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: 'tools/docker/Dockerfile'
          push: false
          tags: 'wrapture'
  sonar-analysis:
    runs-on: ubuntu-latest
    name: SonarCloud analysis
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: sonarsource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONARQUBE_SCANNER_PARAMS: '{"sonar.host.url":"https://sonarcloud.io"}'
  code-analysis:
    runs-on: ubuntu-latest
    name: ruby analysis
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: '3.3'
      - name: Install Dependencies
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop --parallel
      - name: Check RBS
        run: rbs -I sig/ -r pathname validate
      - name: Check RDoc Coverage
        run: bundle exec rdoc --coverage-report lib
